import {
  UtensilsCrossed,
  ShoppingCart,
  ShoppingBag,
  Coffee,
  Wine,
  Home,
  Building2,
  Armchair,
  Zap,
  Droplets,
  Flame,
  Wifi,
  Phone,
  Car,
  Bus,
  TrainFront,
  Fuel,
  Bike,
  Plane,
  BedDouble,
  Ticket,
  Clapperboard,
  Gamepad2,
  Music,
  Tv,
  PartyPopper,
  Heart,
  Cross,
  Pill,
  PersonStanding,
  GraduationCap,
  BookOpen,
  Pencil,
  Briefcase,
  CreditCard,
  Banknote,
  TrendingUp,
  Percent,
  Gift,
  PawPrint,
  Shirt,
  Scissors,
  Wrench,
  Hammer,
  Leaf,
  Users,
  Baby,
  HandHelping,
  Shield,
  FileText,
  Mail,
  Store,
  Tag,
  Star,
  Sparkles,
  CircleEllipsis,
} from 'lucide-react';

export const CATEGORY_LUCIDE_ICONS = {
  utensils: UtensilsCrossed,
  cart: ShoppingCart,
  bag: ShoppingBag,
  cup: Coffee,
  takeout: ShoppingBag,
  wineglass: Wine,
  home: Home,
  building: Building2,
  sofa: Armchair,
  bolt: Zap,
  drop: Droplets,
  flame: Flame,
  wifi: Wifi,
  phone: Phone,
  car: Car,
  bus: Bus,
  tram: TrainFront,
  fuelpump: Fuel,
  bicycle: Bike,
  airplane: Plane,
  bed: BedDouble,
  ticket: Ticket,
  film: Clapperboard,
  gamecontroller: Gamepad2,
  music: Music,
  tv: Tv,
  party: PartyPopper,
  heart: Heart,
  crosscase: Cross,
  pills: Pill,
  figure: PersonStanding,
  graduationcap: GraduationCap,
  book: BookOpen,
  pencil: Pencil,
  briefcase: Briefcase,
  creditcard: CreditCard,
  banknote: Banknote,
  chart: TrendingUp,
  percent: Percent,
  gift: Gift,
  pawprint: PawPrint,
  tshirt: Shirt,
  scissors: Scissors,
  wrench: Wrench,
  hammer: Hammer,
  leaf: Leaf,
  baby: Users,
  stroller: Baby,
  handraised: HandHelping,
  shield: Shield,
  doc: FileText,
  envelope: Mail,
  cartbadge: ShoppingCart,
  storefront: Store,
  tag: Tag,
  star: Star,
  sparkles: Sparkles,
  ellipsis: CircleEllipsis,
};

export function resolveLucideIcon(iconId) {
  return CATEGORY_LUCIDE_ICONS[iconId] || CircleEllipsis;
}
